---
title: "Layouts for officer's PowerPoint document."
author: "Zygmunt Zawadzki"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(customLayout)
library(officer)
library(magrittr)
library(ggplot2)

lay = layCreate(matrix(1:4,nc=2),widths=c(3,2),heights=c(2,1))
lay2 = layCreate(matrix(1:3))
titleLay <- layCreate(1, widths = 1, heights = 1)

lay3 = layColBind(lay,lay2, widths=c(3,1))
layout <- layRowBind(titleLay, lay3, heights = c(1,7))

layShow(layout)
```


```{r}

## create officer layout
offLayout <- phl_layout(layout,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

my_pres <- read_pptx() %>%
  add_slide(master = "Office Theme", layout = "Title and Content")

### fill first placeholder

plot1 <- qplot(mpg, wt, data = mtcars)
plot3 <- qplot(mpg, qsec, data = mtcars)
my_pres <- phl_with_gg(my_pres, offLayout, 2, plot1)
my_pres <- phl_with_gg(my_pres, offLayout, 4, plot3)

pl5 <- function() {
  par(mar = rep(0.1, 4))
  pie(c(3, 4, 6), col = 2:4)
}
pl6 <- function() {
  par(mar = rep(0.1, 4))
  pie(c(3, 2, 7), col = 2:4 + 3)
}
pl7 <- function() {
  par(mar = rep(0.1, 4))
  pie(c(5, 4, 2), col = 2:4 + 6)
}

my_pres <- phl_with_plot(my_pres, offLayout, 6, pl5)
my_pres <- phl_with_plot(my_pres, offLayout, 7, pl6)
my_pres <- phl_with_plot(my_pres, offLayout, 8, pl7)

```

```{r}
my_pres <- phl_with_text(my_pres, offLayout, 1, "Custom Layout")
my_pres <- phl_with_text(my_pres, offLayout, 3, "Some text", type = "body")
my_pres <- phl_with_text(my_pres, offLayout, 5, "Lorem ipsum", type = "body")


```

```{r, eval=FALSE}
print(my_pres, "../tmp/officer-test-3.pptx")
```